#!/bin/sh

while read local_ref local_sha remote_ref remote_sha
do
    # get les fichiers commits
    FILES=$(git diff --name-status $remote_sha $local_sha)
    
    # permet de les parcourir
    echo "$FILES" | while read STATUS FILE; do
        # A = added
        if [ "$STATUS" = "A" ]; then
          if echo "$FILE" | grep -q '^Content/' && ! echo "$FILE" | grep -q '^Content/CanyonCarnage/'; then
              echo "❌ Veuillez retirer vos dossiers/fichiers dans Content/ ! Merci de les placer dans Content/CanyonCarnage/..."
              exit 1
          fi
        fi
    done
done