#!/bin/sh
# Vérifie uniquement les fichiers ajoutés ou modifiés localement avant push
echo "Pre-push hook running..."

while read local_ref local_sha remote_ref remote_sha
do
    # Liste tous les fichiers modifiés dans les commits qui vont être poussés
    FILES=$(git diff --name-only $remote_sha $local_sha)
    
    for FILE in $FILES; do
        if echo "$FILE" | grep -q '^Content/'; then
            echo "❌ You cannot push files or folders in Content/!"
            exit 1
        fi
    done
done